---
title: Mickel Edwards
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: 'This is the personal portfolio site for Mickel Edwards. Industrial designer
  at Iowa  State University.

'
baseurl: ''
url: http://yourdomain.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
permalink: none
categories:
- project

plugins:
- jekyll-menus